// <auto-generated />
using System;
using Assislicitacao.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Assislicitacao.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250716000727_AdicionadoRelacionamentoEmpresaUsuario")]
    partial class AdicionadoRelacionamentoEmpresaUsuario
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Assislicitacao.Models.Empresa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("EMP_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CNPJ")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("EMP_CNPJ");

                    b.Property<int>("EnderecoId")
                        .HasColumnType("int")
                        .HasColumnName("EMP_END_ID");

                    b.Property<int>("PorteEmrpesaId")
                        .HasColumnType("int")
                        .HasColumnName("EMP_PTE_ID");

                    b.Property<string>("RazaoSocial")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("EMP_RAZAO_SOCIAL");

                    b.HasKey("Id");

                    b.HasIndex("CNPJ")
                        .IsUnique();

                    b.HasIndex("EnderecoId");

                    b.HasIndex("PorteEmrpesaId");

                    b.ToTable("EMPRESAS");
                });

            modelBuilder.Entity("Assislicitacao.Models.Endereco", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("END_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Bairro")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("END_BAIRRO");

                    b.Property<string>("CEP")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("END_CEP");

                    b.Property<string>("Complemento")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("END_COMPLEMENTO");

                    b.Property<string>("Logradouro")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("END_LOGRADOURO");

                    b.Property<int>("MunicipioId")
                        .HasColumnType("int")
                        .HasColumnName("END_MUC_ID");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("END_NUMERO");

                    b.HasKey("Id");

                    b.HasIndex("MunicipioId");

                    b.ToTable("ENDERECOS");
                });

            modelBuilder.Entity("Assislicitacao.Models.Estado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("EST_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Uf")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("EST_UF");

                    b.HasKey("Id");

                    b.HasIndex("Uf")
                        .IsUnique();

                    b.ToTable("ESTADOS");
                });

            modelBuilder.Entity("Assislicitacao.Models.Licitacao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("LCT_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime2")
                        .HasColumnName("LCT_DATA");

                    b.Property<int?>("EmpresaId")
                        .HasColumnType("int");

                    b.Property<int>("MunicipioId")
                        .HasColumnType("int")
                        .HasColumnName("LCT_MUC_ID");

                    b.Property<string>("Objeto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("LCT_OBJETO");

                    b.Property<int>("PortalLicitacaoId")
                        .HasColumnType("int")
                        .HasColumnName("LCT_PTL_ID");

                    b.Property<int>("StatusLicitacaoId")
                        .HasColumnType("int")
                        .HasColumnName("LCT_STL_ID");

                    b.Property<int>("TipoLicitacaoId")
                        .HasColumnType("int")
                        .HasColumnName("LCT_TPL_ID");

                    b.Property<decimal?>("ValorEstimado")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("LCT_VALOR_ESTIMADO");

                    b.HasKey("Id");

                    b.HasIndex("EmpresaId");

                    b.HasIndex("MunicipioId");

                    b.HasIndex("PortalLicitacaoId");

                    b.HasIndex("StatusLicitacaoId");

                    b.HasIndex("TipoLicitacaoId");

                    b.ToTable("LICITACOES");
                });

            modelBuilder.Entity("Assislicitacao.Models.LicitacaoEmpresa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("LCEM_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("ConfirmacaoParticipacao")
                        .HasColumnType("bit")
                        .HasColumnName("LCEM_CONFIRMACAO_PARTICIPACAO");

                    b.Property<int>("EmpresaId")
                        .HasColumnType("int")
                        .HasColumnName("LCEM_EMP_ID");

                    b.Property<int>("LicitacaoId")
                        .HasColumnType("int")
                        .HasColumnName("LCEM_LCT_ID");

                    b.HasKey("Id");

                    b.HasIndex("EmpresaId");

                    b.HasIndex("LicitacaoId");

                    b.ToTable("LICITACOES_EMPRESAS");
                });

            modelBuilder.Entity("Assislicitacao.Models.Municipio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MUC_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EstadoId")
                        .HasColumnType("int")
                        .HasColumnName("MUC_USU_ID");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("MUC_NOME");

                    b.HasKey("Id");

                    b.HasIndex("EstadoId");

                    b.HasIndex("Nome", "EstadoId")
                        .IsUnique();

                    b.ToTable("MUNICIPIOS");
                });

            modelBuilder.Entity("Assislicitacao.Models.PortalLicitacao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("PTL_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("PTL_NOME");

                    b.Property<string>("link")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("PTL_LINK");

                    b.HasKey("Id");

                    b.ToTable("PORTAIS_LICITACAO");
                });

            modelBuilder.Entity("Assislicitacao.Models.PorteEmpresa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("PTE_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Porte")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("PTE_PORTE");

                    b.HasKey("Id");

                    b.HasIndex("Porte")
                        .IsUnique();

                    b.ToTable("PORTES_EMPRESA");
                });

            modelBuilder.Entity("Assislicitacao.Models.StatusLicitacao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("STL_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("STL_STATUS");

                    b.HasKey("Id");

                    b.ToTable("STATUS_LICITACAO");
                });

            modelBuilder.Entity("Assislicitacao.Models.TipoLicitacao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("TPL_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Sigla")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("TPL_SIGLA");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("TPL_TIPO");

                    b.HasKey("Id");

                    b.ToTable("TIPOS_LICITACAO");
                });

            modelBuilder.Entity("Assislicitacao.Models.TipoUsuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("TPU_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("TPU_TIPO");

                    b.HasKey("Id");

                    b.ToTable("TIPOS_USUARIO");
                });

            modelBuilder.Entity("Assislicitacao.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("USU_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("USU_EMAIL");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("USU_NOME");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("USU_SENHA");

                    b.Property<int>("TipoId")
                        .HasColumnType("int")
                        .HasColumnName("USU_TPU_ID");

                    b.HasKey("Id");

                    b.HasIndex("TipoId");

                    b.ToTable("USUARIOS");
                });

            modelBuilder.Entity("EmpresaUsuario", b =>
                {
                    b.Property<int>("EmpresasVinculadasId")
                        .HasColumnType("int");

                    b.Property<int>("UsusariosVinculadosId")
                        .HasColumnType("int");

                    b.HasKey("EmpresasVinculadasId", "UsusariosVinculadosId");

                    b.HasIndex("UsusariosVinculadosId");

                    b.ToTable("EmpresaUsuario");
                });

            modelBuilder.Entity("Assislicitacao.Models.Empresa", b =>
                {
                    b.HasOne("Assislicitacao.Models.Endereco", "Endereco")
                        .WithMany("Empresas")
                        .HasForeignKey("EnderecoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Assislicitacao.Models.PorteEmpresa", "PorteEmpresa")
                        .WithMany("Empresas")
                        .HasForeignKey("PorteEmrpesaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Endereco");

                    b.Navigation("PorteEmpresa");
                });

            modelBuilder.Entity("Assislicitacao.Models.Endereco", b =>
                {
                    b.HasOne("Assislicitacao.Models.Municipio", "Municipio")
                        .WithMany("Enderecos")
                        .HasForeignKey("MunicipioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Municipio");
                });

            modelBuilder.Entity("Assislicitacao.Models.Licitacao", b =>
                {
                    b.HasOne("Assislicitacao.Models.Empresa", null)
                        .WithMany("Licitacoes")
                        .HasForeignKey("EmpresaId");

                    b.HasOne("Assislicitacao.Models.Municipio", "Municipio")
                        .WithMany()
                        .HasForeignKey("MunicipioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Assislicitacao.Models.PortalLicitacao", "PortalLicitacao")
                        .WithMany("Licitacoes")
                        .HasForeignKey("PortalLicitacaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Assislicitacao.Models.StatusLicitacao", "StatusLicitacao")
                        .WithMany("Licitacoes")
                        .HasForeignKey("StatusLicitacaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Assislicitacao.Models.TipoLicitacao", "TipoLicitacao")
                        .WithMany("Licitacoes")
                        .HasForeignKey("TipoLicitacaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Municipio");

                    b.Navigation("PortalLicitacao");

                    b.Navigation("StatusLicitacao");

                    b.Navigation("TipoLicitacao");
                });

            modelBuilder.Entity("Assislicitacao.Models.LicitacaoEmpresa", b =>
                {
                    b.HasOne("Assislicitacao.Models.Empresa", "Empresa")
                        .WithMany()
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Assislicitacao.Models.Licitacao", "Licitacao")
                        .WithMany("Empresas")
                        .HasForeignKey("LicitacaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Empresa");

                    b.Navigation("Licitacao");
                });

            modelBuilder.Entity("Assislicitacao.Models.Municipio", b =>
                {
                    b.HasOne("Assislicitacao.Models.Estado", "Estado")
                        .WithMany("Municipios")
                        .HasForeignKey("EstadoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Estado");
                });

            modelBuilder.Entity("Assislicitacao.Models.Usuario", b =>
                {
                    b.HasOne("Assislicitacao.Models.TipoUsuario", "TipoUsuario")
                        .WithMany("Usuarios")
                        .HasForeignKey("TipoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TipoUsuario");
                });

            modelBuilder.Entity("EmpresaUsuario", b =>
                {
                    b.HasOne("Assislicitacao.Models.Empresa", null)
                        .WithMany()
                        .HasForeignKey("EmpresasVinculadasId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Assislicitacao.Models.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UsusariosVinculadosId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Assislicitacao.Models.Empresa", b =>
                {
                    b.Navigation("Licitacoes");
                });

            modelBuilder.Entity("Assislicitacao.Models.Endereco", b =>
                {
                    b.Navigation("Empresas");
                });

            modelBuilder.Entity("Assislicitacao.Models.Estado", b =>
                {
                    b.Navigation("Municipios");
                });

            modelBuilder.Entity("Assislicitacao.Models.Licitacao", b =>
                {
                    b.Navigation("Empresas");
                });

            modelBuilder.Entity("Assislicitacao.Models.Municipio", b =>
                {
                    b.Navigation("Enderecos");
                });

            modelBuilder.Entity("Assislicitacao.Models.PortalLicitacao", b =>
                {
                    b.Navigation("Licitacoes");
                });

            modelBuilder.Entity("Assislicitacao.Models.PorteEmpresa", b =>
                {
                    b.Navigation("Empresas");
                });

            modelBuilder.Entity("Assislicitacao.Models.StatusLicitacao", b =>
                {
                    b.Navigation("Licitacoes");
                });

            modelBuilder.Entity("Assislicitacao.Models.TipoLicitacao", b =>
                {
                    b.Navigation("Licitacoes");
                });

            modelBuilder.Entity("Assislicitacao.Models.TipoUsuario", b =>
                {
                    b.Navigation("Usuarios");
                });
#pragma warning restore 612, 618
        }
    }
}
