USE ASSISLICITACAO;

INSERT TIPOs_PESSOA(TPP_Tipo) VALUES ('Procurador');
INSERT TIPOs_PESSOA(TPP_TIpo) VALUES ('Usuario');
INSERT TIPOs_PESSOA(TPP_Tipo) VALUES ('Sócio');

INSERT USUARIOS(USU_Login,USU_Senha,USU_PSO_Id) VALUES ('jpgeotto', 'jp12042004', 3);