USE Assisliticacao;

--Trigrama = HLCT
CREATE TABLE HISTORICO_LICITACOES(
	HLCT_ID INT NOT NULL,
	HLCT_NUMERO VARCHAR(50) NOT NULL,
	HLCT_OBJETO VARCHAR(150) NOT NULL,
	HLCT_DATA DATE NOT NULL,
	HLCT_ESTIMADO DECIMAL(10,2),
	HLCT_CONFIRMACAO BIT NOT NULL,
	HLCT_CID_ID INT NOT NULL,
	HLCT_PRT_ID INT NOT NULL,
	HLCT_TPL_ID INT NOT NULL,
	HLCT_TDP_ID INT NOT NULL,
	H_DT_ENTRADA DATE NOT NULL,
);

