USE Assisliticacao;

--Trigrama = TPU
CREATE TABLE TIPOS_USUARIO(
	TPU_ID INT IDENTITY,
	TPU_TIPO VARCHAR(30) NOT NULL UNIQUE,
	CONSTRAINT PK_TIPOS_USUARIO PRIMARY KEY(TPU_ID)
);

--Trigrama = USU
CREATE TABLE USUARIOS(
	USU_ID INT IDENTITY,
	USU_NOME VARCHAR(300) NOT NULL,
	USU_SENHA VARCHAR(500) NOT NULL,
	USU_EML_ID INT NOT NULL,
	USU_TPU_ID INT NOT NULL
	CONSTRAINT PK_USUARIO PRIMARY KEY(USU_ID),
	CONSTRAINT FK_USUARIO_EMAIL FOREIGN KEY(USU_EML_ID) REFERENCES EMAILS(EML_ID),
	CONSTRAINT FK_USUARIOS_TIPO FOREIGN KEY(USU_TPU_ID) REFERENCES TIPOS_USUARIO(TPU_ID)
);