USE Assisliticacao;

--Trigrama = END
CREATE TABLE ENDERECOS(
	END_ID INT IDENTITY,
	END_LOGRADOURO VARCHAR(200) NOT NULL,
	END_NUMERO VARCHAR(20) NOT NULL,
	END_CEP VARCHAR(15) NOT NULL,
	END_COMPLEMENTO VARCHAR(200),
	END_BAIRRO VARCHAR(100) NOT NULL,
	END_CID_ID INT NOT NULL,
	CONSTRAINT PK_ENDERECO PRIMARY KEY(END_ID),
	CONSTRAINT FK_ENDERECO_CIDADES FOREIGN KEY(END_CID_ID) REFERENCES CIDADES(CID_ID)
);

--Trigrama = EQD
CREATE TABLE ENQUADRAMENTOS(
	EQD_ID INT IDENTITY,
	EQD_TIPO VARCHAR(100) NOT NULL,
	EQD_SIGLA VARCHAR(20) NOT NULL
	CONSTRAINT PK_EQUADRAMENTOS PRIMARY KEY(EQD_ID)
);

--Trigrama = TLF
CREATE TABLE TELEFONES(
	TLF_ID INT IDENTITY,
	TLF_NUMERO VARCHAR(20)  NOT NULL,
	CONSTRAINT PK_TELEFONES PRIMARY KEY(TLF_ID),
	CONSTRAINT UNQ_NUMERO_TELEFONE UNIQUE(TLF_NUMERO)
);

--Trigrama = EML
CREATE TABLE EMAILS(
	EML_ID INT IDENTITY,
	EML_EMAIL VARCHAR(100) NOT NULL UNIQUE,
	CONSTRAINT PK_EMAILS PRIMARY KEY(EML_ID),
	CONSTRAINT UNQ_EMAIL_EMAILS UNIQUE(EML_EMAIL)

);

--Trigrama = EMP
CREATE TABLE EMPRESAS(
	EMP_ID INT IDENTITY,
	EMP_CNPJ VARCHAR(100) NOT NULL UNIQUE,
	EMP_RAZAO_SOCIAL VARCHAR(300) NOT NULL,
	EMP_NOME_FANTASIA VARCHAR(200),
	EMP_TLF_ID INT NOT NULL,
	EMP_EQD_ID INT NOT NULL,
	EMP_END_ID INT NOT NULL,
	CONSTRAINT PK_EMPRESAS PRIMARY KEY(EMP_ID),
	CONSTRAINT FK_EMPRESAS_TELEFONES FOREIGN KEY(EMP_TLF_ID) REFERENCES TELEFONES(TLF_ID),
	CONSTRAINT FK_EMPRESAS_ENQUADRAMENTOS FOREIGN KEY(EMP_EQD_ID) REFERENCES ENQUADRAMENTOS(EQD_ID),
	CONSTRAINT FK_EMPRESAS_ENDERECOS FOREIGN KEY(EMP_END_ID) REFERENCES ENDERECOS(END_ID)
);

--Trigrama EEP
CREATE TABLE EMAILS_EMPRESAS(
	EEP_EML_ID INT NOT NULL,
	EEP_EMP_ID INT NOT NULL,
	EPP_CONFIRMACAO BIT NOT NULL
	CONSTRAINT PK_EMAILS_EMPRESAS PRIMARY KEY(EEP_EML_ID,EEP_EMP_ID),
	CONSTRAINT FK_EMAIL_EEP FOREIGN KEY(EEP_EML_ID) REFERENCES EMAILS(EML_ID),
	CONSTRAINT FK_EMPRESAS_EPP FOREIGN KEY(EEP_EMP_ID) REFERENCES EMPRESAS(EMP_ID)
);