USE Assisliticacao;

--Trigrama = TPL
CREATE TABLE TIPOS_LICITACAO(
	TPL_ID INT IDENTITY,
	TPL_TIPO VARCHAR(50) NOT NULL,
	TPL_SIGLA CHAR(2) NOT NULL,
	CONSTRAINT PK_TIPOS_LICITACAO PRIMARY KEY (TPL_ID)
);

--Trigrama = PRT
CREATE TABLE PORTAIS(
	PRT_ID INT IDENTITY,
	PRT_NOME VARCHAR(100) NOT NULL,
	PRT_LINK VARCHAR(300) NOT NULL,
	CONSTRAINT PK_PORTAIS PRIMARY KEY (PRT_ID)
);

--Trigrama = TDP
CREATE TABLE TIPOS_DISPUTA(
	TDP_ID INT IDENTITY,
	TDP_TIPO VARCHAR(150) NOT NULL,
	CONSTRAINT PK_TIPOS_DISPUTA PRIMARY KEY(TDP_ID)
);

--Trigrama = LCT
CREATE TABLE LICITACOES(
	LCT_ID INT IDENTITY,
	LCT_NUMERO VARCHAR(50) NOT NULL,
	LCT_OBJETO VARCHAR(150) NOT NULL,
	LCT_DATA DATE NOT NULL,
	LCT_ESTIMADO DECIMAL(10,2),
	LCT_CID_ID INT NOT NULL,
	LCT_PRT_ID INT NOT NULL,
	LCT_TPL_ID INT NOT NULL,
	LCT_TDP_ID INT NOT NULL,
	CONSTRAINT PK_LICITACOES PRIMARY KEY(LCT_ID),
	CONSTRAINT FK_LICITACOES_CIDADES FOREIGN KEY(LCT_CID_ID) REFERENCES CIDADES(CID_ID),
	CONSTRAINT FK_LICITACOES_PORTAIS FOREIGN KEY(LCT_PRT_ID) REFERENCES PORTAIS(PRT_ID),
	CONSTRAINT FK_LICITACOES_TIPO_LICITACAO FOREIGN KEY(LCT_TPL_ID) REFERENCES TIPOS_LICITACAO(TPL_ID),
	CONSTRAINT FK_LICITACOES_TIPO_DISPUTA FOREIGN KEY(LCT_TDP_ID) REFERENCES TIPOS_DISPUTA(TDP_ID)
);

--Trigrama = LEM
CREATE TABLE LICITACOES_EMPRESAS(
	LEM_LCT_ID INT NOT NULL, 
	LEM_EMP_ID INT NOT NULL,
	LEM_CONFIRMACAO BIT NOT NULL,
		LEM_USU_ID INT NOT NULL,
	CONSTRAINT PK_LICITACOES_EMPRESAS PRIMARY KEY(LEM_LCT_ID, LEM_EMP_ID),
	CONSTRAINT FK_LEM_USUARIO FOREIGN KEY (LEM_USU_ID) REFERENCES USUARIOS(USU_ID)
);

--Trigrama = LNP
CREATE TABLE LOGINS_PORTAIS(
	LNP_ID INT NOT NULL,
	LNP_LOGIN VARCHAR(100) NOT NULL,
	LNP_SENHA VARCHAR(100) NOT NULL,
	LNP_PRT_ID INT NOT NULL,
	LNP_EMP_ID INT NOT NULL,
	CONSTRAINT PK_LOGINS_PORTAIS PRIMARY KEY(LNP_ID),
	CONSTRAINT FK_LNP_PORTAL FOREIGN KEY(LNP_PRT_ID) REFERENCES PORTAIS(PRT_ID),
	CONSTRAINT FK_LNP_EMPRESA FOREIGN KEY (LNP_EMP_ID)  REFERENCES EMPRESAS(EMP_ID)
);