USE Assisliticacao;

--trigrama = EST
CREATE TABLE ESTADOS(
	EST_ID INT IDENTITY,
	EST_NOME VARCHAR(100) NOT NULL,
	EST_UF CHAR(2) NOT NULL
	CONSTRAINT PK_ESTADOS PRIMARY KEY(EST_ID),
	CONSTRAINT UQ_ESTADOS_NOME UNIQUE(EST_NOME)
);

--Trigrama = CID
CREATE TABLE CIDADES(
	CID_ID INT IDENTITY,
	CID_NOME VARCHAR(200) NOT NULL,
	CID_EST_ID INT NOT NULL
	CONSTRAINT PK_CIDADES PRIMARY KEY(CID_ID),
	CONSTRAINT FK_CIDADES_ESTADOS FOREIGN KEY(CID_EST_ID) REFERENCES ESTADOS(EST_ID)
);

--Trigrama = ORG
CREATE TABLE ORGAOS(
	ORG_ID INT IDENTITY,
	ORG_NOME VARCHAR(300) NOT NULL,
	ORG_CID_ID INT,
	ORG_EST_ID INT,
	CONSTRAINT PK_ORGAOS PRIMARY KEY(ORG_ID),
	CONSTRAINT FK_ORGAOS_CIDADES FOREIGN KEY(ORG_CID_ID) REFERENCES CIDADES(CID_ID),
	CONSTRAINT FK_ORGAOS_ESTADOS FOREIGN KEY(ORG_EST_ID) REFERENCES ESTADOS(EST_ID)
);