USE Assisliticacao;

INSERT INTO TIPOS_USUARIO(TPU_TIPO) VALUES ('Administrador');
INSERT INTO TIPOS_USUARIO(TPU_TIPO) VALUES ('Assistente de licitação');
INSERT INTO TIPOS_USUARIO(TPU_TIPO) VALUES ('Analista de licitação');
INSERT INTO TIPOS_USUARIO(TPU_TIPO) VALUES ('Sócio');
INSERT INTO TIPOS_USUARIO(TPU_TIPO) VALUES ('Procurador');