USE Assisliticacao;

INSERT INTO ENQUADRAMENTOS(EQD_SIGLA, EQD_TIPO) VALUES ('EPP', 'Empresa de Pequeno Porte');
INSERT INTO ENQUADRAMENTOS(EQD_SIGLA, EQD_TIPO) VALUES ('ME', 'Microempresa');
INSERT INTO ENQUADRAMENTOS(EQD_SIGLA, EQD_TIPO) VALUES ('EI', 'Empresário Individual');
INSERT INTO ENQUADRAMENTOS(EQD_SIGLA, EQD_TIPO) VALUES ('DEMAIS', 'Demais');
INSERT INTO ENQUADRAMENTOS(EQD_SIGLA, EQD_TIPO) VALUES ('OSC', 'Organização da Sociedade Civil');