USE Assisliticacao;



CREATE PROCEDURE PROC_InserirCidades
	@Nome NVARCHAR(300),
	@Uf CHAR(2)
AS 
BEGIN 
	DECLARE @EstadoId INT

	SELECT @EstadoId = EST_ID FROM ESTADOS WHERE EST_UF = @UF;

	IF NOT EXISTS (SELECT 1 FROM CIDADES WHERE CID_NOME = @Nome AND CID_EST_ID = @EstadoId)
	BEGIN
		INSERT INTO CIDADES(CID_NOME, CID_EST_ID) VALUES(@Nome, @EstadoId)
	END
END;

CREATE PROCEDURE InserirDados
AS BEGIN 
	DECLARE @NomeCidade NVARCHAR(300), @UF CHAR(2);

	DECLARE CURSOR_MUNICIPIOS CURSOR FOR
	SELECT NOME, UF FROM municipios;

	OPEN CURSOR_MUNICIPIOS;

	FETCH NEXT FROM CURSOR_MUNICIPIOS INTO @NomeCidade, @UF;

	WHILE @@FETCH_STATUS = 0
		BEGIN
			EXEC PROC_InserirCidades @NomeCidade, @UF
			FETCH NEXT FROM CURSOR_MUNICIPIOS INTO @NomeCidade, @UF;
		END
		
	CLOSE CURSOR_MUNICIPIOS;

	DEALLOCATE CURSOR_MUNICIPIOS;
END 