USE Assisliticacao;

CREATE TRIGGER Tg_VerificarEndereco ON ENDERECOS
INSTEAD OF INSERT 
AS 
BEGIN
	IF EXISTS(
		SELECT 1 FROM ENDERECOS E
		JOIN INSERTED I ON
		UPPER(E.END_LOGRADOURO) = UPPER(I.END_LOGRADOURO) AND
		UPPER(E.END_BAIRRO) = UPPER(I.END_BAIRRO) AND
		E.END_CID_ID = I.END_CID_ID AND
		ISNULL(E.END_COMPLEMENTO, '') = ISNULL(I.END_COMPLEMENTO, '') AND
		E.END_NUMERO = I.END_NUMERO AND
		E.END_CEP = I.END_CEP
	)
	BEGIN
		THROW 50001, 'Endereço já cadastrado', 1;
	END
	ELSE 
	BEGIN 
		INSERT INTO ENDERECOS(END_LOGRADOURO, END_NUMERO, END_CEP, END_BAIRRO, END_CID_ID, END_COMPLEMENTO)
		SELECT END_LOGRADOURO, END_NUMERO, END_CEP, END_BAIRRO, END_CID_ID, END_COMPLEMENTO FROM INSERTED;
	END
END;