USE Assisliticacao;

CREATE TRIGGER TG_VerificarUsuario ON USUARIOS
INSTEAD OF INSERT
AS 
BEGIN
	IF EXISTS(
		SELECT 1 FROM USUARIOS U
		JOIN INSERTED I ON
		U.USU_NOME = I.USU_NOME AND
		U.USU_SENHA = I.USU_SENHA AND
		U.USU_EML_ID = I.USU_EML_ID AND
		U.USU_TPU_ID = I.USU_TPU_ID
	)
		BEGIN
			THROW 50001, 'Usuario já cadastrado', 1; 
		END
	ELSE
		BEGIN
			INSERT INTO USUARIOS(USU_NOME, USU_SENHA, USU_EML_ID, USU_TPU_ID)
			SELECT USU_NOME, USU_SENHA, USU_EML_ID, USU_TPU_ID FROM INSERTED;
		END
END