USE Assisliticacao;

CREATE TRIGGER Tg_VerificarEmail ON EMAILS
INSTEAD OF INSERT
AS
BEGIN
	IF EXISTS(
		SELECT 1 FROM EMAILS E
		JOIN INSERTED I ON
		E.EML_EMAIL = E.EML_EMAIL
	)
	BEGIN
		THROW 50001, 'Email já cadastrado', 1; 
	END
	ELSE
	BEGIN
		INSERT INTO EMAILS(EML_EMAIL)
		SELECT EML_EMAIL FROM INSERTED;
	END
END