USE Assisliticacao;

CREATE TRIGGER TG_His_Licitacoes
ON LICITACOES
INSTEAD OF UPDATE, DELETE
AS BEGIN
	--Caso seja um update
	IF EXISTS(SELECT * FROM INSERTED)
	BEGIN
		INSERT INTO HISTORICO_LICITACOES
		(
			HLCT_ID, 
			HLCT_NUMERO, 
			HLCT_OBJETO, 
			HLCT_DATA, 
			HLCT_ESTIMADO, 
			HLCT_CONFIRMACAO, 
			HLCT_CID_ID, 
			HLCT_PRT_ID, 
			HLCT_TPL_ID, 
			HLCT_TDP_ID, 
			H_DT_ENTRADA
		)
		SELECT 
			I.LCT_ID, 
			I.LCT_NUMERO, 
			I.LCT_OBJETO, 
			I.LCT_DATA, 
			I.LCT_ESTIMADO, 
			I.LCT_CONFIRMACAO, 
			I.LCT_CID_ID, 
			I.LCT_PRT_ID, 
			I.LCT_TPL_ID, 
			I.LCT_TDP_ID, 
			GETDATE()
		FROM INSERTED I;



		UPDATE LICITACOES
		SET  
			LCT_NUMERO = I.LCT_NUMERO,
			LCT_OBJETO = I.LCT_OBJETO, 
			LCT_DATA = I.LCT_DATA, 
			LCT_ESTIMADO = I.LCT_ESTIMADO, 
			LCT_CONFIRMACAO = I.LCT_CONFIRMACAO, 
			LCT_CID_ID = I.LCT_CID_ID, 
			LCT_PRT_ID = I.LCT_PRT_ID, 
			LCT_TPL_ID = I.LCT_TPL_ID, 
			LCT_TDP_ID = I.LCT_TDP_ID
		FROM INSERTED I
		WHERE LICITACOES.LCT_ID = I.LCT_ID;
	END


	--Caso seja um delete
	IF EXISTS(SELECT * FROM DELETED)
	BEGIN
		INSERT INTO HISTORICO_LICITACOES
			(
				HLCT_ID, 
				HLCT_NUMERO, 
				HLCT_OBJETO, 
				HLCT_DATA, 
				HLCT_ESTIMADO, 
				HLCT_CONFIRMACAO, 
				HLCT_CID_ID, 
				HLCT_PRT_ID, 
				HLCT_TPL_ID, 
				HLCT_TDP_ID, 
				H_DT_ENTRADA
			)
			SELECT 
				D.LCT_ID, 
				D.LCT_NUMERO, 
				D.LCT_OBJETO, 
				D.LCT_DATA, 
				D.LCT_ESTIMADO, 
				D.LCT_CONFIRMACAO, 
				D.LCT_CID_ID, 
				D.LCT_PRT_ID, 
				D.LCT_TPL_ID, 
				D.LCT_TDP_ID, 
				GETDATE()
			FROM DELETED D;
		PRINT 'Licitacao foi para o histórico'
		
		DELETE FROM LICITACOES
		WHERE LCT_ID IN (SELECT LCT_ID FROM DELETED);
	END
END

DELETE LICITACOES;

SELECT * FROM HISTORICO_LICITACOES;