USE Assisliticacao;

CREATE TRIGGER Tg_VerificarTelefone ON TELEFONES
INSTEAD OF INSERT
AS
BEGIN
	IF EXISTS(
		SELECT 1 FROM TELEFONES T
		JOIN INSERTED I ON
		T.TLF_NUMERO = I.TLF_NUMERO
	)
	BEGIN
		THROW 50001, 'Telefone já cadastrado', 1; 
	END
	ELSE
	BEGIN
		INSERT INTO TELEFONES(TLF_NUMERO)
		SELECT TLF_NUMERO FROM INSERTED;
	END
END