USE Assisliticacao;

CREATE VIEW vw_LicitacoesDetalhadas
AS
	SELECT 
		LCT_ID,
		EST_ID,
		TPL_ID,
		TDP_ID,
		PRT_ID,
		CID_ID,
		TPL_SIGLA, 
		LCT_NUMERO, 
		LCT_OBJETO, 
		LCT_DATA, 
		TDP_TIPO, 
		LCT_ESTIMADO, 
		LCT_CONFIRMACAO, 
		CID_NOME, 
		EST_UF, 
		PRT_NOME, 
		PRT_LINK
	FROM LICITACOES
	JOIN CIDADES ON LCT_CID_ID = CID_ID
	JOIN ESTADOS ON CID_EST_ID = EST_ID
	JOIN TIPOS_LICITACAO ON LCT_TPL_ID = TPL_ID
	JOIN PORTAIS ON LCT_PRT_ID = PRT_ID


CREATE View Vw_DadosEmpresa AS
	SELECT * FROM EMPRESAS
	JOIN TELEFONES ON TLF_ID = EMP_TLF_ID
	JOIN ENQUADRAMENTOS ON EQD_ID = EMP_EQD_ID
	JOIN ENDERECOS ON END_ID = EMP_END_ID
	JOIN CIDADES ON CID_ID = END_CID_ID
	JOIN ESTADOS ON EST_ID = CID_EST_ID;