USE Assisliticacao;

CREATE VIEW vw_LicitacoesDetalhadas
AS
	SELECT 
		TPL_SIGLA, LCT_NUMERO, LCT_OBJETO, LCT_DATA, TDP_TIPO, LCT_ESTIMADO, LCT_CONFIRMACAO, CID_NOME, EST_UF, PRT_NOME, PRT_LINK
	FROM LICITACOES
	JOIN CIDADES ON LCT_CID_ID = CID_ID
	JOIN ESTADOS ON CID_EST_ID = EST_ID
	JOIN TIPOS_LICITACAO ON LCT_TPL_ID = TPL_ID
	JOIN PORTAIS ON LCT_PRT_ID = PRT_ID
	JOIN TIPOS_DISPUTA ON LCT_TDP_ID = TDP_ID;