CREATE TRIGGER TG_ATUALIZAR_VALORGANHO_STATUS_LICITACAO
ON LICITACOES_EMPRESAS
AFTER UPDATE
AS
BEGIN
    SET NOCOUNT ON;

    
    IF UPDATE(LCEM_VALOR_GANHO)
    BEGIN
       
        UPDATE L
        SET L.LCT_STL_ID = S.STL_ID
        FROM LICITACOES L
        INNER JOIN LICITACOES_EMPRESAS LE ON L.LCT_ID = LE.LCEM_LCT_ID
        CROSS JOIN STATUS_LICITACAO S
        INNER JOIN inserted I ON I.LCEM_ID = LE.LCEM_ID
        WHERE S.STL_STATUS = 'ADJUDICADA/HOMOLAGADA';
    END
END
